[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/"
]

[start]
cmd = "npm start --prefix backend"
